server:
  port: 9090

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuerUri: http://localhost:8082/realms/DigitalMedia
        registration:
          api-gateway:
            provider: keycloak
            clientId: api-gateway
            clientSecret: Ls3dEXkMtSOaimFzCCbJAVWpgMNJOv54
            authorizationGrantType: authorization_code
            redirectUri: 'http://localhost:9090/login/oauth2/code/DigitalMedia'
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: users-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: movies-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/movies/**
          filters:
            - StripPrefix=2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true